### ISSUE TITLE
Statements for core queries

### ISSUE THREAD

**Issue by zachgharst** [ZDGharst/CS470_MostFunGroup#3]
Example: This gives us the closest cities to the location (40.69, -73.92)

```
 SELECT id,
       NAME,
       Sqrt(( latitude - 40.69 ) * ( latitude - 40.69 ) +
            ( longitude + 73.92 ) * ( longitude + 73.92 )) AS distance
FROM   city
ORDER  BY distance;  
```

You can replace the lat/long coordinates with variables.

```
 SELECT id,
       mag,
       Sqrt(( latitude - 40.69 ) * ( latitude - 40.69 ) + ( longitude + 73.92 )
            * (
            longitude + 73.92 )) AS distance
FROM   earthquake
ORDER  BY distance;  
```

Closest earthquake to a coordinate pair.

**Comment by ZDGharst** [comment]
` SELECT id,
       mag,
       Sqrt(( latitude - 40.69 ) * ( latitude - 40.69 ) +
            ( longitude + 73.92 ) * ( longitude + 73.92 )) AS distance
FROM   earthquake
ORDER  BY distance;  `

**Comment by ZDGharst** [comment]
SELECT id,
       mag,
       Sqrt(( latitude - 40.69 ) * ( latitude - 40.69 ) +
            ( longitude + 73.92 ) * ( longitude + 73.92 )) AS distance
FROM   earthquake
ORDER  BY distance;

**Comment by zachgharst** [comment]
@MattMiller1989 has refactored one of our queries!
 ```
 SELECT earthquake.id,
       mag,
       St_distance_sphere(Point(earthquake.longitude, earthquake.latitude),
       Point(city.longitude, city.latitude)) * .000621371192 AS distance
FROM   earthquake
       INNER JOIN city
               ON name = 'New York'
ORDER  BY distance;  
```

**Comment by MattMiller1989** [comment]
This one enables you to figure out which countries are NOT within a certain range of an earthquake of a certain magnitude

<font face="Courier New" size="2">
<font color = "blue">SELECT</font>&nbsp;<font color = "blue">DISTINCT</font>&nbsp;<font color = "maroon">city</font><font color = "silver">.</font><font color = "maroon">country</font>
<br/><font color = "blue">FROM</font>&nbsp;&nbsp;&nbsp;<font color = "maroon">city</font>
<br/><font color = "blue">WHERE</font>&nbsp;&nbsp;<font color = "maroon">city</font><font color = "silver">.</font><font color = "maroon">country</font>&nbsp;<font color = "blue">NOT</font>&nbsp;<font color = "blue">IN</font>&nbsp;<font color = "maroon">(</font><font color = "blue">SELECT</font>&nbsp;<font color = "blue">DISTINCT</font>&nbsp;<font color = "maroon">t1</font><font color = "silver">.</font><font color = "maroon">country</font>
<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color = "blue">FROM</font>&nbsp;&nbsp;&nbsp;<font color = "maroon">(</font><font color = "blue">SELECT</font>&nbsp;<font color = "maroon">city</font><font color = "silver">.</font><font color = "maroon">country</font><font color = "silver">,</font>
<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color = "#FF0080"><b>St_distance_sphere</b></font><font color = "maroon">(</font><font color = "#FF0080"><b>Point</b></font><font color = "maroon">(</font>
<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color = "maroon">earthquake</font><font color = "silver">.</font><font color = "maroon">longitude</font><font color = "silver">,</font>
<br/><font color = "maroon">earthquake</font><font color = "silver">.</font><font color = "maroon">latitude</font><font color = "maroon">)</font><font color = "silver">,</font>
<br/><font color = "#FF0080"><b>Point</b></font><font color = "maroon">(</font><font color = "maroon">city</font><font color = "silver">.</font><font color = "maroon">longitude</font><font color = "silver">,</font>&nbsp;<font color = "maroon">city</font><font color = "silver">.</font><font color = "maroon">latitude</font><font color = "maroon">)</font><font color = "maroon">)</font>&nbsp;<font color = "silver">*</font>
<br/><font color = "black">.000621371192</font>&nbsp;<font color = "blue">AS</font>
<br/><font color = "maroon">distance</font>
<br/><font color = "blue">FROM</font>&nbsp;&nbsp;&nbsp;<font color = "maroon">earthquake</font><font color = "silver">,</font>
<br/><font color = "maroon">city</font>
<br/><font color = "blue">WHERE</font>&nbsp;&nbsp;<font color = "maroon">earthquake</font><font color = "silver">.</font><font color = "maroon">mag</font>&nbsp;<font color = "silver">&gt;</font>&nbsp;<font color = "black">5.0</font>
<br/><font color = "blue">HAVING</font>&nbsp;<font color = "maroon">distance</font>&nbsp;<font color = "silver">&lt;</font>&nbsp;<font color = "black">500.0</font><font color = "maroon">)</font>&nbsp;<font color = "maroon">t1</font><font color = "maroon">)</font><font color = "silver">;</font>&nbsp;
</font>
